# Generated by Django 3.0.3 on 2020-11-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_created=True)),
                ('identificador', models.CharField(max_length=55, verbose_name='Utilizador')),
                ('palavra_passe', models.CharField(max_length=128, verbose_name='Palavra-passe')),
                ('modificado_em', models.DateField(editable=False)),
                ('estado', models.CharField(choices=[('P', 'PENDENTE'), ('I', 'INATIVO'), ('A', 'ATIVO')], default='PENDENTE', max_length=1)),
            ],
        ),
    ]
