# Generated by Django 3.0.3 on 2020-11-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('criado_em', models.DateTimeField(auto_created=True, default='2020-11-26 18:18:29.992081')),
                ('usuario', models.CharField(max_length=55, primary_key=True, serialize=False, unique=True, verbose_name='Utilizador')),
                ('palavra_passe', models.CharField(max_length=128, verbose_name='Palavra-passe')),
                ('modificado_em', models.DateTimeField(editable=False)),
                ('estado', models.CharField(choices=[('P', 'PENDENTE'), ('I', 'INATIVO'), ('A', 'ATIVO')], default='PENDENTE', max_length=1)),
                ('chave', models.CharField(editable=False, max_length=255)),
            ],
            options={
                'ordering': ['usuario', 'palavra_passe'],
            },
        ),
    ]
