# Generated by Django 3.0.3 on 2020-11-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='criado_em',
            field=models.DateTimeField(auto_created=True, default='2020-11-29 15:36:27.171035'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='modificado_em',
            field=models.DateTimeField(default='2020-11-29 15:36:27.171035', editable=False),
        ),
    ]
