# Generated by Django 3.0.3 on 2020-11-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20201129_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastro',
            options={'ordering': ['usuario', 'estado']},
        ),
        migrations.RenameField(
            model_name='cadastro',
            old_name='palavra_passe',
            new_name='senha',
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='criado_em',
            field=models.DateTimeField(auto_created=True, default='2020-11-29 15:59:52.338596'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='modificado_em',
            field=models.DateTimeField(default='2020-11-29 15:59:52.338596', editable=False),
        ),
    ]
