# Generated by Django 3.1.6 on 2021-02-12 19:59

import artigo.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('designacao', models.CharField(default='', max_length=55, unique=True, verbose_name='Designação')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(default=None, height_field='Image.altura', unique=True, upload_to=artigo.models.diretorio_artigo, verbose_name='Imagem', width_field='Image.altura')),
                ('largura', models.IntegerField(editable=False)),
                ('altura', models.IntegerField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(blank=True, default='Ref_00', max_length=55, verbose_name='Referencia')),
                ('nome', models.CharField(default='Sumo', max_length=55, verbose_name='Produto')),
                ('preco', models.FloatField(default='0.00', max_length=55, verbose_name='Preço')),
                ('moeda', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dollar'), ('MZN', 'Metical'), ('ZAR', 'Rand')], default='EUR', max_length=3, verbose_name='Moeda')),
                ('quantidade', models.FloatField(default='1.0', max_length=55, verbose_name='Quantidade')),
                ('unidade', models.CharField(choices=[('gr', 'Gramas'), ('kg', 'Quilogramas'), ('fa', 'Fatias'), ('lt', 'Litros')], default='kg', max_length=2, verbose_name='Unidades')),
                ('descricao', models.TextField(default='Simples descrição do artigo', max_length=256, verbose_name='Descrição')),
                ('categoria', models.OneToOneField(max_length=55, on_delete=django.db.models.deletion.DO_NOTHING, to='artigo.categoria', to_field='designacao')),
                ('foto', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='artigo.image', to_field='foto')),
            ],
        ),
    ]
