# Generated by Django 3.1.7 on 2021-02-22 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao', models.CharField(default='', max_length=55, unique=True, verbose_name='Designação')),
            ],
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(blank=True, default='Ref_00', max_length=55, verbose_name='Referencia')),
                ('foto', models.ImageField(default=None, upload_to='', verbose_name='Imagem')),
                ('nome', models.CharField(default='Sumo', max_length=55, verbose_name='Produto')),
                ('preco', models.FloatField(default='0.00', max_length=55, verbose_name='Preço')),
                ('moeda', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dollar'), ('MZN', 'Metical'), ('ZAR', 'Rand')], default='EUR', max_length=3, verbose_name='Moeda')),
                ('quantidade', models.FloatField(default='1.0', max_length=55, verbose_name='Quantidade')),
                ('unidade', models.CharField(choices=[('gr', 'Gramas'), ('kg', 'Quilogramas'), ('fa', 'Fatias'), ('lt', 'Litros')], default='kg', max_length=2, verbose_name='Unidades')),
                ('descricao', models.TextField(default='Simples descrição do produto', max_length=256, verbose_name='Descrição')),
                ('categoria', models.ForeignKey(max_length=55, on_delete=django.db.models.deletion.DO_NOTHING, to='artigo.categoria', to_field='designacao')),
            ],
        ),
    ]
