# Generated by Django 3.1.7 on 2021-02-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artigo',
            old_name='test',
            new_name='foto',
        ),
        migrations.AlterField(
            model_name='artigo',
            name='unidade',
            field=models.CharField(choices=[('gr', 'Gramas'), ('kg', 'Quilogramas'), ('fa', 'Fatias'), ('lt', 'Litros'), ('ml', 'Militros')], default='kg', max_length=2, verbose_name='Unidades'),
        ),
    ]
