# Generated by Django 3.1.7 on 2021-02-23 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artigo', '0002_auto_20210223_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='categoria',
            field=models.ForeignKey(max_length=55, on_delete=django.db.models.deletion.DO_NOTHING, to='artigo.categoria', to_field='designacao'),
        ),
    ]
